import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";

const pretendard = localFont({
    src: [
        {
            path: "../assets/fonts/Pretendard-Regular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../assets/fonts/Pretendard-Medium.woff2",
            weight: "500",
            style: "normal",
        },
    ],
    variable: "--font-pretendard",
});

const sebang_gothic = localFont({
    src: "../assets/fonts/SEBANGGothic.ttf",
    variable: "--font-sebang-gothic",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${pretendard.variable} ${sebang_gothic.variable} antialiased dark:bg-gray1000`}
            >
                <Header />
                {children}
            </body>
        </html>
    );
}
